/**
 * AddEventModal - Modal for adding calendar events for team members
 *
 * Provides a form to create availability periods for team members with:
 * - Member selection from existing team members
 * - Status selection (available, unavailable, school, vacation)
 * - Date range selection with validation
 * - Optional notes for context
 *
 * @example
 * ```tsx
 * const [isOpen, setIsOpen] = useState(false);
 * <AddEventModal open={isOpen} onOpenChange={setIsOpen} />
 * ```
 */

'use client';

import * as React from 'react';
import { useState } from 'react';
import { CalendarPlus } from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogBody,
  DialogFooter,
} from '@/components/ui/Dialog';
import { Button } from '@/components/ui/Button';
import { useCalendarStore } from '@/lib/store';
import { AvailabilityStatus, STATUS_COLORS } from '@/lib/types';
import { format } from 'date-fns';

/**
 * AddEventModal props
 */
export interface AddEventModalProps {
  /** Whether the modal is open */
  open: boolean;
  /** Callback when the open state changes */
  onOpenChange: (open: boolean) => void;
}

/**
 * Get today's date in YYYY-MM-DD format for input[type="date"]
 * @returns Today's date as string in YYYY-MM-DD format
 */
const getTodayString = (): string => {
  return format(new Date(), 'yyyy-MM-dd');
};

/**
 * AddEventModal component
 *
 * Features:
 * - Member dropdown selection (required)
 * - Visual status selection with color-coded buttons (required)
 * - Date range picker with validation (end >= start)
 * - Optional note/description field
 * - Form validation with disabled submit until required fields filled
 * - Auto-reset on submit and close
 *
 * @param props - Modal properties
 */
export function AddEventModal({ open, onOpenChange }: AddEventModalProps) {
  // ========== Store Access ==========
  const addEvent = useCalendarStore((state) => state.addEvent);
  const members = useCalendarStore((state) => state.members);

  // ========== Form State ==========
  const [selectedMemberId, setSelectedMemberId] = useState('');
  const [status, setStatus] = useState<AvailabilityStatus>('school');
  const [startDate, setStartDate] = useState(getTodayString());
  const [endDate, setEndDate] = useState(getTodayString());
  const [note, setNote] = useState('');

  /**
   * Reset all form fields to initial state
   */
  const resetForm = () => {
    setSelectedMemberId('');
    setStatus('school');
    setStartDate(getTodayString());
    setEndDate(getTodayString());
    setNote('');
  };

  /**
   * Handle form submission
   * - Validates required fields
   * - Creates event in store
   * - Resets form
   * - Closes modal
   */
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    // Validate required fields
    if (!selectedMemberId || !startDate || !endDate) {
      return;
    }

    // Add event to store
    addEvent({
      id: '', // ID will be auto-generated by store
      memberId: selectedMemberId,
      startDate: new Date(startDate),
      endDate: new Date(endDate),
      status,
      note: note.trim() || undefined,
      isImported: false,
    });

    // Reset form and close modal
    resetForm();
    onOpenChange(false);
  };

  /**
   * Handle modal close
   * Reset form when closing to avoid showing stale data on next open
   */
  const handleOpenChange = (newOpen: boolean) => {
    if (!newOpen) {
      resetForm();
    }
    onOpenChange(newOpen);
  };

  /**
   * Check if submit button should be disabled
   * Requires: member selected + start date + end date
   */
  const isSubmitDisabled = !selectedMemberId || !startDate || !endDate;

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent>
        {/* Header */}
        <DialogHeader>
          <div className="flex items-center gap-2 mb-2">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center">
              <CalendarPlus className="w-4 h-4 text-white" />
            </div>
            <DialogTitle>Ajouter une période</DialogTitle>
          </div>
          <DialogDescription>
            Définissez la disponibilité d&apos;un membre
          </DialogDescription>
        </DialogHeader>

        {/* Form */}
        <form onSubmit={handleSubmit}>
          <DialogBody>
            <div className="space-y-4">
              {/* Member Selection (Required) */}
              <div className="space-y-2">
                <label htmlFor="event-member" className="text-sm font-medium text-foreground">
                  Membre <span className="text-red-500">*</span>
                </label>
                <select
                  id="event-member"
                  value={selectedMemberId}
                  onChange={(e) => setSelectedMemberId(e.target.value)}
                  className="w-full px-3 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                  required
                >
                  <option value="">Sélectionner un membre</option>
                  {members.map((member) => (
                    <option key={member.id} value={member.id}>
                      {member.name} - {member.role}
                    </option>
                  ))}
                </select>
              </div>

              {/* Status Selection (Required) */}
              <div className="space-y-2">
                <label className="text-sm font-medium text-foreground">
                  Statut <span className="text-red-500">*</span>
                </label>
                <div className="grid grid-cols-2 gap-2">
                  {(Object.keys(STATUS_COLORS) as AvailabilityStatus[]).map((statusOption) => {
                    const isSelected = status === statusOption;
                    const colors = STATUS_COLORS[statusOption];

                    return (
                      <button
                        key={statusOption}
                        type="button"
                        onClick={() => setStatus(statusOption)}
                        className={`
                          px-4 py-3 rounded-md text-sm font-medium transition-all
                          ${colors.bg} ${colors.text} ${colors.border}
                          ${isSelected
                            ? 'border-2 shadow-md ring-2 ring-offset-2 ring-primary'
                            : 'border hover:shadow-sm'
                          }
                        `}
                      >
                        {colors.label}
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* Date Range (Required) */}
              <div className="grid grid-cols-2 gap-4">
                {/* Start Date */}
                <div className="space-y-2">
                  <label htmlFor="event-start-date" className="text-sm font-medium text-foreground">
                    Date de début <span className="text-red-500">*</span>
                  </label>
                  <input
                    id="event-start-date"
                    type="date"
                    value={startDate}
                    onChange={(e) => {
                      setStartDate(e.target.value);
                      // If end date is before new start date, update it
                      if (endDate < e.target.value) {
                        setEndDate(e.target.value);
                      }
                    }}
                    className="w-full px-3 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                    required
                  />
                </div>

                {/* End Date */}
                <div className="space-y-2">
                  <label htmlFor="event-end-date" className="text-sm font-medium text-foreground">
                    Date de fin <span className="text-red-500">*</span>
                  </label>
                  <input
                    id="event-end-date"
                    type="date"
                    value={endDate}
                    min={startDate}
                    onChange={(e) => setEndDate(e.target.value)}
                    className="w-full px-3 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                    required
                  />
                </div>
              </div>

              {/* Note (Optional) */}
              <div className="space-y-2">
                <label htmlFor="event-note" className="text-sm font-medium text-foreground">
                  Note
                </label>
                <textarea
                  id="event-note"
                  rows={2}
                  placeholder="Ex: Semaine de cours à HETIC"
                  value={note}
                  onChange={(e) => setNote(e.target.value)}
                  className="w-full px-3 py-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all resize-none"
                />
              </div>
            </div>
          </DialogBody>

          {/* Footer */}
          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
            >
              Annuler
            </Button>
            <Button
              type="submit"
              variant="primary"
              disabled={isSubmitDisabled}
            >
              Ajouter
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

AddEventModal.displayName = 'AddEventModal';
