/**
 * AddMemberModal - Modal for adding new team members
 *
 * Provides a form to add new team members with name, role, and rotation pattern.
 * Automatically assigns colors from the predefined palette and resets on submission.
 *
 * @example
 * ```tsx
 * const [isOpen, setIsOpen] = useState(false);
 * <AddMemberModal open={isOpen} onOpenChange={setIsOpen} />
 * ```
 */

'use client';

import * as React from 'react';
import { useState } from 'react';
import { UserPlus } from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogBody,
  DialogFooter,
} from '@/components/ui/Dialog';
import { Button } from '@/components/ui/Button';
import { useCalendarStore } from '@/lib/store';
import { MEMBER_COLORS } from '@/lib/types';

/**
 * AddMemberModal props
 */
export interface AddMemberModalProps {
  /** Whether the modal is open */
  open: boolean;
  /** Callback when the open state changes */
  onOpenChange: (open: boolean) => void;
}

/**
 * Default rotation pattern for new members
 */
const DEFAULT_ROTATION_PATTERN = '3 semaines entreprise, 1 semaine école';

/**
 * AddMemberModal component
 *
 * Features:
 * - Required name field with validation
 * - Optional role field (defaults to 'Alternant')
 * - Rotation pattern with default value
 * - Auto-assigns color from palette based on member count
 * - Form reset after successful submission
 * - Accessible form with proper labels and ARIA attributes
 *
 * @param props - Modal properties
 */
export function AddMemberModal({ open, onOpenChange }: AddMemberModalProps) {
  // ========== Store Actions ==========
  const addMember = useCalendarStore((state) => state.addMember);
  const members = useCalendarStore((state) => state.members);

  // ========== Form State ==========
  const [name, setName] = useState('');
  const [role, setRole] = useState('');
  const [rotationPattern, setRotationPattern] = useState(DEFAULT_ROTATION_PATTERN);

  /**
   * Handle form submission
   * - Validates name is not empty
   * - Assigns color from palette (cycles through colors)
   * - Adds member to store
   * - Resets form
   * - Closes modal
   */
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    // Validate name is not empty
    if (!name.trim()) {
      return;
    }

    // Calculate color based on current member count (cycles through palette)
    const colorIndex = members.length % MEMBER_COLORS.length;
    const color = MEMBER_COLORS[colorIndex];

    // Add member to store
    addMember({
      id: '', // ID will be auto-generated by store
      name: name.trim(),
      role: role.trim() || 'Alternant', // Default to 'Alternant' if empty
      color,
      rotationPattern: rotationPattern.trim(),
    });

    // Reset form to initial state
    setName('');
    setRole('');
    setRotationPattern(DEFAULT_ROTATION_PATTERN);

    // Close modal
    onOpenChange(false);
  };

  /**
   * Handle modal close
   * Reset form when closing to avoid showing stale data on next open
   */
  const handleOpenChange = (newOpen: boolean) => {
    if (!newOpen) {
      // Reset form when closing
      setName('');
      setRole('');
      setRotationPattern(DEFAULT_ROTATION_PATTERN);
    }
    onOpenChange(newOpen);
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="max-w-md sm:max-w-lg">
        {/* Header */}
        <DialogHeader className="p-4 sm:p-6 pb-3 sm:pb-4">
          <div className="flex items-center gap-2 mb-2">
            <div className="w-7 h-7 sm:w-8 sm:h-8 rounded-lg bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center flex-shrink-0">
              <UserPlus className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-white" />
            </div>
            <DialogTitle className="text-base sm:text-lg">Ajouter un membre</DialogTitle>
          </div>
          <DialogDescription className="text-xs sm:text-sm">
            Ajoutez un nouveau membre à l&apos;équipe
          </DialogDescription>
        </DialogHeader>

        {/* Form */}
        <form onSubmit={handleSubmit}>
          <DialogBody className="p-4 sm:p-6 pt-0">
            <div className="space-y-3 sm:space-y-4">
              {/* Name Field (Required) */}
              <div className="space-y-1.5 sm:space-y-2">
                <label htmlFor="member-name" className="text-xs sm:text-sm font-medium text-foreground block">
                  Nom complet <span className="text-red-500">*</span>
                </label>
                <input
                  id="member-name"
                  type="text"
                  placeholder="Ex: Jean Dupont"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  className="w-full px-3 py-2.5 sm:py-3 text-sm sm:text-base border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                  autoFocus
                  required
                />
              </div>

              {/* Role Field (Optional) */}
              <div className="space-y-1.5 sm:space-y-2">
                <label htmlFor="member-role" className="text-xs sm:text-sm font-medium text-foreground block">
                  Rôle
                </label>
                <input
                  id="member-role"
                  type="text"
                  placeholder="Ex: Développeur Full-Stack"
                  value={role}
                  onChange={(e) => setRole(e.target.value)}
                  className="w-full px-3 py-2.5 sm:py-3 text-sm sm:text-base border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                />
              </div>

              {/* Rotation Pattern Field */}
              <div className="space-y-1.5 sm:space-y-2">
                <label htmlFor="member-rotation" className="text-xs sm:text-sm font-medium text-foreground block">
                  Rythme d&apos;alternance
                </label>
                <input
                  id="member-rotation"
                  type="text"
                  placeholder="Ex: 3 semaines entreprise, 1 semaine école"
                  value={rotationPattern}
                  onChange={(e) => setRotationPattern(e.target.value)}
                  className="w-full px-3 py-2.5 sm:py-3 text-sm sm:text-base border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all"
                />
              </div>
            </div>
          </DialogBody>

          {/* Footer */}
          <DialogFooter className="p-4 sm:p-6 pt-3 sm:pt-4 flex-col-reverse sm:flex-row gap-2 sm:gap-3">
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              className="w-full sm:w-auto"
            >
              Annuler
            </Button>
            <Button
              type="submit"
              variant="primary"
              disabled={!name.trim()}
              className="w-full sm:w-auto"
            >
              Ajouter
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

AddMemberModal.displayName = 'AddMemberModal';
